### PR TITLE
Fix single port NICs bug for link type attribte

### LINKED ISSUE #48: Network config daemon crashing with Mellanox ConnectX4LX
This seems related to https://github.com/openshift/sriov-network-operator/issues/43 but the error message is slightly different.

I am trying to setup our kubevirt CI to use the sriov operator instead of setting up manually. The tests run using a kind cluster but I don't think this is relevant since the output of the mstconfig tool is the same on the bare metal host.

I am testing with a mellanox ConnectX4LX card: 
```
mstconfig -d 0000:05:00.1 q 

Device #1:
----------

Device type:    ConnectX4LX     
Name:           N/A             
Description:    N/A             
Device:         0000:05:00.1 
```

Which do not happen to have the LINK_TYPE properties nor LINK_TYPE_P1:
```
[root@zeus08 kubevirt]# mstconfig -d 0000:05:00.1 q | grep LINK
         KEEP_ETH_LINK_UP_P1                 True(1)         
         KEEP_IB_LINK_UP_P1                  False(0)        
         KEEP_LINK_UP_ON_BOOT_P1             False(0)        
         KEEP_LINK_UP_ON_STANDBY_P1          False(0)        
         KEEP_ETH_LINK_UP_P2                 True(1)         
         KEEP_IB_LINK_UP_P2                  False(0)        
         KEEP_LINK_UP_ON_BOOT_P2             False(0)        
         KEEP_LINK_UP_ON_STANDBY_P2          False(0) 
```

This is causing the `sriov-network-config-daemon` to crash because `isSinglePortNic` [is returning an error](https://github.com/openshift/sriov-network-operator/blob/master/pkg/plugins/mellanox/mellanox_plugin.go#L271) .

config daemon logs:
```
I0731 16:50:14.687456    6475 writer.go:107] setNodeStateStatus(): syncStatus: InProgress, lastSyncError: 
E0731 16:50:14.744306    6475 mellanox_plugin.go:163] mellanox-plugin mstconfigReadData(): failed : exit status 3 : 
Device #1:
----------

Device type:    ConnectX4LX     
Name:           N/A             
Description:    N/A             
Device:         0000:05:00.0    

Configurations:                              Next Boot
-E- Unknown Parameter: LINK_TYPE
I0731 16:50:14.744344    6475 mellanox_plugin.go:157] mellanox-plugin mstconfigReadData(): try to read [LINK_TYPE_P2] for device 0000:05:00.0
I0731 16:50:14.744363    6475 mellanox_plugin.go:169] mellanox-plugin runCommand(): mstconfig [-d 0000:05:00.0 q LINK_TYPE_P2]
E0731 16:50:14.819727    6475 mellanox_plugin.go:163] mellanox-plugin mstconfigReadData(): failed : exit status 3 : 
Device #1:
----------

Device type:    ConnectX4LX     
Name:           N/A             
Description:    N/A             
Device:         0000:05:00.0    

Configurations:                              Next Boot
-E- The Device doesn't support LINK_TYPE_P2 parameter
E0731 16:50:14.819765    6475 daemon.go:147] nodeStateAddHandler(): plugin mellanox_plugin error: exit status 3
I0731 16:50:14.819810    6475 daemon.go:240] nodeStateChangeHandler(): Interface not changed
```

### PR DESCRIPTION
**Pull request by Mmduh-483**
Fixes #48

### CODE REVIEW

File: pkg/plugins/mellanox/mellanox_plugin.go [hunk 1]
```diff
@@ -238,7 +223,7 @@ func mlnxNicFromMap(mstData map[string]string, singlePort, firstPort bool) (*mln
 	} else if strings.Contains(linkType, InfinibandLinkType) {
 		fwData.linkType = InfinibandLinkType
 	} else {
-		return nil, fmt.Errorf("mellanox-plugin getMlnxNicFwData(): Unknown link type %s", linkType)
+		glog.Warningf("mellanox-plugin getMlnxNicFwData(): Couldn't read link type %s, preconfigured NIC", linkType)
```
Comment (adrianchiris) [inline pkg/plugins/mellanox/mellanox_plugin.go]: Why is it a preconfigured NIC if  linkType is not Infiniband nor Ethernet ?

File: pkg/plugins/mellanox/mellanox_plugin.go [hunk 2]
```diff
@@ -225,9 +212,7 @@ func mlnxNicFromMap(mstData map[string]string, singlePort, firstPort bool) (*mln
 		return nil, err
 	}
 	fwData.totalVfs = i
-	if fwData.singlePort {
-		linkType = mstData["LINK_TYPE"]
-	} else if fwData.firstPort {
+	if fwData.firstPort {
 		linkType = mstData["LINK_TYPE_P1"]
```
Comment (adrianchiris) [inline pkg/plugins/mellanox/mellanox_plugin.go]: What will happen if LINK_TYPE_P1 is not in the map ?
in case the link type is not configurable, the map will not contain LINK_TYPE_P1 norLINK_TYPE_P2 entries.

File: pkg/plugins/mellanox/mellanox_plugin.go [hunk 3]
```diff
@@ -176,46 +172,37 @@ func runCommand(command string, args ...string) (string, error) {
...
 	}
 	return
 }
 
-func mlnxNicFromMap(mstData map[string]string, singlePort, firstPort bool) (*mlnxNic, error) {
-	glog.Infof("mellanox-plugin mlnxNicFromMap() %v, %v, %v", mstData, singlePort, firstPort)
-	fwData := &mlnxNic{singlePort: singlePort, firstPort: firstPort}
+func mlnxNicFromMap(mstData map[string]string, firstPort bool) (*mlnxNic, error) {
+	glog.Infof("mellanox-plugin mlnxNicFromMap() %v, %v", mstData, firstPort)
+	fwData := &mlnxNic{firstPort: firstPort}
```
Comment (adrianchiris) [inline pkg/plugins/mellanox/mellanox_plugin.go]: TBH, i dont think mlxNic struct should contain first port attribute.
it should contain the PCI address and a bound method of getPortNum()

File: pkg/plugins/mellanox/mellanox_plugin.go [hunk 4]
```diff
@@ -225,9 +212,7 @@ func mlnxNicFromMap(mstData map[string]string, singlePort, firstPort bool) (*mln
 		return nil, err
 	}
 	fwData.totalVfs = i
-	if fwData.singlePort {
-		linkType = mstData["LINK_TYPE"]
-	} else if fwData.firstPort {
+	if fwData.firstPort {
 		linkType = mstData["LINK_TYPE_P1"]
 	} else {
 		linkType = mstData["LINK_TYPE_P2"]
```
Comment (adrianchiris) [inline pkg/plugins/mellanox/mellanox_plugin.go]: Same as above

File: pkg/plugins/mellanox/mellanox_plugin.go (hunk 1 above)
Comment (adrianchiris) [reply pkg/plugins/mellanox/mellanox_plugin.go]: Id expect two different warnings to be emitted in getMlnxNicFwData()

1.  LINK_TYPE_P* attribute was found in the map but it is not one of [ETH, IB]
2. LINK_TYPE_P* attribute was not found in the map

File: pkg/plugins/mellanox/mellanox_plugin.go [hunk 5]
```diff
@@ -176,46 +172,37 @@ func runCommand(command string, args ...string) (string, error) {
...
-		} else {
-			attrs = append(attrs, "LINK_TYPE_P2")
-		}
+		attrs = append(attrs, "LINK_TYPE_P2")
 	}
-	out, err := mstconfigReadData(pciAddress, attrs...)
+	out, err := mstConfigReadData(pciAddress)
 	if err != nil {
 		return
 		glog.Errorf("mellanox-plugin getMlnxNicFwData(): %v", err)
```
Comment (adrianchiris) [inline pkg/plugins/mellanox/mellanox_plugin.go]: dead code, move above return, also the content should express that we failed to query mstconfig

File: pkg/plugins/mellanox/mellanox_plugin.go [hunk 6]
```diff
@@ -149,17 +146,16 @@ func configFW() error {
...
+		glog.Infof("mellanox-plugin configFW(): %s", out)
 	}
 	return nil
 }
 
-func mstconfigReadData(pciAddress string, attributes ...string) (string, error) {
-	glog.Infof("mellanox-plugin mstconfigReadData(): try to read %s for device %s", attributes, pciAddress)
-
+func mstConfigReadData(pciAddress string) (string, error) {
+	glog.Infof("mellanox-plugin mstConfigReadData(): device %s", pciAddress)
```
Comment (adrianchiris) [inline pkg/plugins/mellanox/mellanox_plugin.go]: debug print?

File: pkg/plugins/mellanox/mellanox_plugin.go [hunk 7]
```diff
@@ -149,17 +146,16 @@ func configFW() error {
...
 	args := []string{"-e", "-d", pciAddress, "q"}
-	args = append(args, attributes...)
 	out, err := runCommand("mstconfig", args...)
-	glog.Info("mellanox-plugin mstconfigReadData(): %s", out)
+	glog.Info("mellanox-plugin mstConfigReadData(): %s", out)
```
Comment (adrianchiris) [inline pkg/plugins/mellanox/mellanox_plugin.go]: debug print?

File: pkg/plugins/mellanox/mellanox_plugin.go [hunk 8]
```diff
@@ -149,17 +146,16 @@ func configFW() error {
...
 }
 
-func mstconfigReadData(pciAddress string, attributes ...string) (string, error) {
-	glog.Infof("mellanox-plugin mstconfigReadData(): try to read %s for device %s", attributes, pciAddress)
-
+func mstConfigReadData(pciAddress string) (string, error) {
+	glog.Infof("mellanox-plugin mstConfigReadData(): device %s", pciAddress)
 	args := []string{"-e", "-d", pciAddress, "q"}
-	args = append(args, attributes...)
 	out, err := runCommand("mstconfig", args...)
```
Comment (adrianchiris) [inline pkg/plugins/mellanox/mellanox_plugin.go]: Also, can we make the Info print a debug print in runCommand ?

File: pkg/plugins/mellanox/mellanox_plugin.go (hunk 6 above)
Comment (adrianchiris) [reply pkg/plugins/mellanox/mellanox_plugin.go]: you can use an increased verbosity level for these logs (same goes to the rest of my logging comments)

see:
https://godoc.org/github.com/golang/glog#V

File: pkg/plugins/mellanox/mellanox_plugin.go (hunk 2 above)
Comment (Mmduh-483) [reply pkg/plugins/mellanox/mellanox_plugin.go]: A warning will appear, check line 226

File: pkg/plugins/mellanox/mellanox_plugin.go (hunk 5 above)
Comment (Mmduh-483) [reply pkg/plugins/mellanox/mellanox_plugin.go]: fixed

File: pkg/plugins/mellanox/mellanox_plugin.go (hunk 1 above)
Comment (Mmduh-483) [reply pkg/plugins/mellanox/mellanox_plugin.go]: fixed

File: pkg/plugins/mellanox/mellanox_plugin.go (hunk 3 above)
Comment (Mmduh-483) [reply pkg/plugins/mellanox/mellanox_plugin.go]: The port number can only be 0 or 1, there is no need to create the function getPortNumber, instead, I will move isFirtPort function to the struct

File: pkg/plugins/mellanox/mellanox_plugin.go (hunk 4 above)
Comment (Mmduh-483) [reply pkg/plugins/mellanox/mellanox_plugin.go]: Same as above

File: pkg/plugins/mellanox/mellanox_plugin.go (hunk 6 above)
Comment (Mmduh-483) [reply pkg/plugins/mellanox/mellanox_plugin.go]: fixed

File: pkg/plugins/mellanox/mellanox_plugin.go (hunk 7 above)
Comment (Mmduh-483) [reply pkg/plugins/mellanox/mellanox_plugin.go]: fixed

File: pkg/plugins/mellanox/mellanox_plugin.go (hunk 8 above)
Comment (Mmduh-483) [reply pkg/plugins/mellanox/mellanox_plugin.go]: good idea

**Comment by Mmduh-483** [comment]
@adrianchiris pushed the fixes
